# This file was generated by GoReleaser. DO NOT EDIT.
cask "calliope" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9e7175f273641e8b0e31e146f7c06618f32465763151df555028bc4bd5740aa3"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "84c65c78601191faca96aa006d94ccf47f7b841c954cca364a038d56cd9d2b73"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8df82650012625f89d4798e944d482b1f59214f99df91248978fe52d7a3b974f"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe591ac09ac6a5a017757fcc54f4374db40ee6279916f8c59b6eba55c0306f62"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_linux_amd64.tar.gz"
    end
  end

  name "calliope"
  desc "CLI de Calliope Data"
  homepage "https://github.com/Calliope-AI/calliope-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calliope"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calliope"]
    end
  end

  # No zap stanza required
end
