# This file was generated by GoReleaser. DO NOT EDIT.
cask "calliope" do
  version "0.0.1-test"

  on_macos do
    on_arm do
      sha256 "6e86b3c071d27b41753a1630a2edd6ce08a56a5152491a388775a4840ab8ebc8"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d46359d9afadce08d915842f842cc30287d4015aa5184892c2f126f510ba5b14"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2d4146486ca4bae20ecd3e9c28a1e37862a2e6b9a4e4c7d4504427e6c7279e7f"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0128bec962a8b55aee33c5e695eed60832c3d9b952349edc41abc465d0c35fa5"
      url "https://github.com/Calliope-AI/calliope-cli/releases/download/v#{version}/calliope_#{version}_linux_amd64.tar.gz"
    end
  end

  name "calliope"
  desc "CLI de Calliope Data"
  homepage "https://github.com/Calliope-AI/calliope-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calliope"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calliope"]
    end
  end

  # No zap stanza required
end
